// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/ervitis/sink-float/master/adapter/handlers/grpc"
	"github.com/ervitis/sink-float/master/config"
	"github.com/ervitis/sink-float/master/repository"
	"github.com/ervitis/sink-float/master/usecases"
	"github.com/google/wire"
)

// Injectors from wire.go:

func HandleGRPCHandlerProvider(cfg config.AppConfig) GRPCHandlers {
	memcache := repository.NewMemcache()
	sinkUseCase := usecases.NewSinkUseCase(memcache)
	sinkFleetServiceServer := grpc.NewSinkFleetHandler(sinkUseCase)
	grpcHandlers := NewGRPCHandlers(sinkFleetServiceServer)
	return grpcHandlers
}

// wire.go:

var repositoriesSet = wire.NewSet(repository.NewMemcache)

var usecasesSet = wire.NewSet(
	repositoriesSet, usecases.NewSinkUseCase,
)

type GRPCHandlers struct {
	SinkHandler grpc.SinkFleetHandler
}

func NewGRPCHandlers(sinkFleetHandler grpc.SinkFleetHandler) GRPCHandlers {
	return GRPCHandlers{
		SinkHandler: sinkFleetHandler,
	}
}
