// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: sinkfleet.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAlive bool `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
}

func (x *Alive) Reset() {
	*x = Alive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinkfleet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alive) ProtoMessage() {}

func (x *Alive) ProtoReflect() protoreflect.Message {
	mi := &file_sinkfleet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alive.ProtoReflect.Descriptor instead.
func (*Alive) Descriptor() ([]byte, []int) {
	return file_sinkfleet_proto_rawDescGZIP(), []int{0}
}

func (x *Alive) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type MissileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *MissileRequest) Reset() {
	*x = MissileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinkfleet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissileRequest) ProtoMessage() {}

func (x *MissileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sinkfleet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissileRequest.ProtoReflect.Descriptor instead.
func (*MissileRequest) Descriptor() ([]byte, []int) {
	return file_sinkfleet_proto_rawDescGZIP(), []int{1}
}

func (x *MissileRequest) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MissileRequest) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AtomicMissile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuessNumber uint32 `protobuf:"varint,1,opt,name=guessNumber,proto3" json:"guessNumber,omitempty"`
}

func (x *AtomicMissile) Reset() {
	*x = AtomicMissile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinkfleet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomicMissile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicMissile) ProtoMessage() {}

func (x *AtomicMissile) ProtoReflect() protoreflect.Message {
	mi := &file_sinkfleet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicMissile.ProtoReflect.Descriptor instead.
func (*AtomicMissile) Descriptor() ([]byte, []int) {
	return file_sinkfleet_proto_rawDescGZIP(), []int{2}
}

func (x *AtomicMissile) GetGuessNumber() uint32 {
	if x != nil {
		return x.GuessNumber
	}
	return 0
}

type MissileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hit bool `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
}

func (x *MissileResponse) Reset() {
	*x = MissileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinkfleet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissileResponse) ProtoMessage() {}

func (x *MissileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sinkfleet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissileResponse.ProtoReflect.Descriptor instead.
func (*MissileResponse) Descriptor() ([]byte, []int) {
	return file_sinkfleet_proto_rawDescGZIP(), []int{3}
}

func (x *MissileResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

type KillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Missile uint64 `protobuf:"varint,1,opt,name=missile,proto3" json:"missile,omitempty"`
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinkfleet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sinkfleet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_sinkfleet_proto_rawDescGZIP(), []int{4}
}

func (x *KillRequest) GetMissile() uint64 {
	if x != nil {
		return x.Missile
	}
	return 0
}

var File_sinkfleet_proto protoreflect.FileDescriptor

var file_sinkfleet_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x69, 0x6e, 0x6b, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x73, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x69, 0x73, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x01, 0x79, 0x22, 0x31, 0x0a, 0x0d, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x75, 0x65, 0x73, 0x73,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x75,
	0x65, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x0f, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x68, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x68, 0x69, 0x74, 0x22, 0x27,
	0x0a, 0x0b, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6c, 0x65, 0x32, 0x8a, 0x01, 0x0a, 0x16, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x69, 0x6e, 0x6b, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x69, 0x63, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6c, 0x65, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x73, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x22, 0x00, 0x32, 0x53, 0x0a, 0x11, 0x53, 0x68, 0x69, 0x70, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x53, 0x65, 0x6e,
	0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sinkfleet_proto_rawDescOnce sync.Once
	file_sinkfleet_proto_rawDescData = file_sinkfleet_proto_rawDesc
)

func file_sinkfleet_proto_rawDescGZIP() []byte {
	file_sinkfleet_proto_rawDescOnce.Do(func() {
		file_sinkfleet_proto_rawDescData = protoimpl.X.CompressGZIP(file_sinkfleet_proto_rawDescData)
	})
	return file_sinkfleet_proto_rawDescData
}

var file_sinkfleet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sinkfleet_proto_goTypes = []interface{}{
	(*Alive)(nil),           // 0: proto.Alive
	(*MissileRequest)(nil),  // 1: proto.MissileRequest
	(*AtomicMissile)(nil),   // 2: proto.AtomicMissile
	(*MissileResponse)(nil), // 3: proto.MissileResponse
	(*KillRequest)(nil),     // 4: proto.KillRequest
	(*emptypb.Empty)(nil),   // 5: google.protobuf.Empty
}
var file_sinkfleet_proto_depIdxs = []int32{
	2, // 0: proto.MasterSinkFleetService.Attack:input_type -> proto.AtomicMissile
	5, // 1: proto.MasterSinkFleetService.CheckIsAlive:input_type -> google.protobuf.Empty
	4, // 2: proto.ShipClientService.SendClientKill:input_type -> proto.KillRequest
	3, // 3: proto.MasterSinkFleetService.Attack:output_type -> proto.MissileResponse
	0, // 4: proto.MasterSinkFleetService.CheckIsAlive:output_type -> proto.Alive
	5, // 5: proto.ShipClientService.SendClientKill:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sinkfleet_proto_init() }
func file_sinkfleet_proto_init() {
	if File_sinkfleet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sinkfleet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinkfleet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinkfleet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtomicMissile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinkfleet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinkfleet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sinkfleet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sinkfleet_proto_goTypes,
		DependencyIndexes: file_sinkfleet_proto_depIdxs,
		MessageInfos:      file_sinkfleet_proto_msgTypes,
	}.Build()
	File_sinkfleet_proto = out.File
	file_sinkfleet_proto_rawDesc = nil
	file_sinkfleet_proto_goTypes = nil
	file_sinkfleet_proto_depIdxs = nil
}
